# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
# This workflow deploys the app on push or pull request

name: Update Copa do Brasil

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
  - cron: "59 23 * 3-10 3-5"
  workflow_dispatch:

jobs:
  deploy:
    name: Update Copa do Brasil
    runs-on: ubuntu-18.04

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      RSPM: ${{ matrix.config.rspm }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Instalando libs de sistema
        run: |
          sudo apt update
          sudo apt install libudunits2-dev libgdal-dev
          sudo apt install libprotobuf-dev protobuf-compiler
          sudo apt install libjq-dev
          sudo add-apt-repository ppa:cran/libgit2
          sudo apt-get install libgit2-dev
      
      - name: Cache R packages
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-shinydoc
          restore-keys: |
            ${{ runner.os }}-
      - name: Install packages
        shell: Rscript {0}
        run: |
          install.packages(c("xml2","purrr","tidyverse",
          "rvest", "stringr", "lubridate"))
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore(repos = "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest")
            
      - name: Scrape and update
        run: |
          Rscript Docs/Copa_Brasil_Matches_Update.R
      - name: Commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add . || echo "No changes to commit"
          git commit -m 'updating matches' || echo "No changes to commit"
          git push origin || echo "No changes to commit"