# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
# This workflow deploys the app on push or pull request

name: Update Brasileirao

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
  - cron: "59 23 * 5-12 3-4,6,1"
  workflow_dispatch:

jobs:
  deploy:
    name: Update Brasileirao
    runs-on: windows-latest

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      RSPM: ${{ matrix.config.rspm }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Scrape and update
        run: |
          Rscript data-raw/Update_Brasileirao.R
      - name: Commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add . || echo "No changes to commit"
          git commit -m 'updating matches' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
